# Resolve react_native_pods.rb with node to allow for hoisting
use_modular_headers! # Add this line globally


require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'YORAA07092004' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'YORAA07092004Tests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end





#
# # Resolve react_native_pods.rb correctly
# require_relative '../node_modules/react-native/scripts/react_native_pods'
#
# # Define minimum iOS version
# platform :ios, '13.0' # Update to the minimum supported iOS version for your project
#
# prepare_react_native_project!
#
# # Configure frameworks linking
# linkage = ENV['USE_FRAMEWORKS'] || 'static'
# Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
# use_frameworks! :linkage => linkage.to_sym
#
# target 'YORAA07092004' do
#   # Use native modules and React Native setup
#   config = use_native_modules!
#
#   use_react_native!(
#     :path => config[:reactNativePath],
#     # An absolute path to your application root.
#         :hermes_enabled => true, # Ensure Hermes is enabled if needed
#
#     :app_path => "#{Pod::Config.instance.installation_root}/.."
#   )
#
#   # Test target configuration
#   target 'YORAA07092004Tests' do
#     inherit! :complete
#     # Pods for testing
#   end
#
#   # Post-install configurations
#   post_install do |installer|
#     # React Native post-install setup
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false
#     )
#
#     # Exclude arm64 architecture for simulator
#     installer.pods_project.targets.each do |target|
#       target.build_configurations.each do |config|
#         config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
#       end
#     end
#   end
# end

